// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'itemIcon': string;
  'menuButton': string;
  'user': string;
  'userAvatar': string;
  'userAvatarIcon': string;
  'userDetails': string;
  'userGroup': string;
  'userGroups': string;
  'userName': string;
  'userSecondary': string;
}
export const cssExports: CssExports;
export default cssExports;
